name: Eslint
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: develop
    - name: Install modules
      run: yarn
    - name: Run ESLint
      run: yarn lint